name: Deploy Vite React App to GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        env:
          VITE_DEPLOYMENT_ID: ${{ secrets.VITE_DEPLOYMENT_ID }}  
        run: npm run build

      - name: Copy CNAME to dist
        run: cp CNAME dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

